braille/urls.py
from django.contrib import admin
from django.urls.conf import include, path
from django.conf.urls.static import settings, static

from .views import (AboutView, HelpView, IndexView,
                    SignUpView, UserDetailView)
                     #ScanView,

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    #path('contact/', ContactView.as_view(), name='contact'),
    path('help/', HelpView.as_view(), name='help'),
   # path('scan/', ScanView.as_view(), name='scan'),

    path('profile/<slug:pk>/', UserDetailView.as_view(), name='profile'),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('contact/', include('contact.urls')),
    path('scanimg', include('scanimg.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 
 # accounts/login/
    # accounts/logout/
    # accounts/password_change/
    # accounts/password_reset/
    # accounts/login/

contact/urls.py
from django.urls.conf import path

from contact.views import ContactCreateView

app_name = 'contact'

urlpatterns = [
    path('', ContactCreateView.as_view(), name='contact-us'),
]

scanimg/urls.py
from django.urls.conf import path

from . import views

app_name = 'scanimg'

urlpatterns = [
    path('', views.scan, name='photo'),
]

contact/models.py
from django.core.validators import RegexValidator
from django.db import models


# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=63)
    phone = models.CharField(
        max_length=14,
        validators=[
            RegexValidator(
                regex='01[0-9]{9}',
                message='Please provide a valid phone number',
            ),
        ],
        blank=True
    )
    email = models.EmailField()
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.name is not None:
            return self.name

scanimg/models.py
from django.conf import settings

from django.db import models


class Image(models.Model):
    caption=models.CharField(max_length=100)
    image=models.ImageField(upload_to='img/%y')
    def __str__(self):
     return self.image

braille/views.py
from django.contrib.auth.models import User
from django.forms.models import BaseModelForm
from django import forms
from django.http import HttpRequest
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import CreateView, DetailView, TemplateView, FormView


class IndexView(TemplateView):
    template_name = 'index.html'


class AboutView(TemplateView):
    template_name = 'about.html'


#class ContactView(TemplateView):
    #template_name = 'contact.html'


class HelpView(TemplateView):
    template_name = 'help.html'


# class ScanForm(forms.Form):
   # image = forms.ImageField(allow_empty_file=False, required=True)


# class ScanView(FormView):
    #form_class = ScanForm
  #  template_name = 'scan.html'
    #success_url = '/scan'

  #  def post(self, request: HttpRequest, *args: str, **kwargs: str):
       # image = request.FILES.get('image')
        #return super().post(request, *args, **kwargs)


class SignUpView(CreateView):
    model = User
    fields = ['username', 'first_name', 'last_name', 'email', 'password']
    template_name = 'signup.html'
    success_url = '/'
    success_message = 'Account created successfully!'
    error_message = 'Account creation failed!'

    def form_valid(self, form: BaseModelForm):
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password'])
        user.save()

        return super(SignUpView, self).form_valid(form)

    def get(self, request: HttpRequest, *args: str, **kwargs: str):
        if request.user.is_authenticated:
            return redirect('/')

        return super(SignUpView, self).get(request, *args, **kwargs)

    def post(self, request: HttpRequest, *args: str, **kwargs: str):
        if request.user.is_authenticated:
            return redirect('/')

        return super(SignUpView, self).post(request, *args, **kwargs)


class UserDetailView(DetailView):
    model = User

    def get(self, request: HttpRequest, *args: str, **kwargs: str):
        user = get_object_or_404(User, username=kwargs.get('pk'))

        return render(request, template_name='profile.html', context={'user': user})

contact/views.py
from django.views.generic.edit import CreateView
from django.shortcuts import redirect, render

from contact.models import Contact


# Create your views here.
class ContactCreateView(CreateView):
    model = Contact
    fields = '__all__'
    success_url = '/'

scanimg/views.py
from django.shortcuts import render,redirect
from .form import ImageForm
from .models import Image

# Create your views here.


def scan(request):
    if request.method == "POST":
        form=ImageForm(data=request.POST,files=request.FILES)
        if form.is_valid():
            form.save()
            obj=form.instance
            return render(request,"scan.html",{"obj":obj})
    else:
          form=ImageForm()
          img=Image.objects.all()
    return render(request,"scan.html",{"img":img,"form":form})





# class ScanView(FormView):
    #form_class = ScanForm
  #  template_name = 'scan.html'
    #success_url = '/scan'

  #  def post(self, request: HttpRequest, *args: str, **kwargs: str):
       # image = request.FILES.get('image')
        #return super().post(request, *args, **kwargs)

contact/templates/contact/contact_form.html
{% extends 'main.html' %}

{% block content %}
<div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="flex items-center min-h-screen">
        <div class="container mx-auto">
            <div class="max-w-lg mx-auto my-10 bg-white p-5 rounded-md shadow-sm">
                <div class="text-center">
                    <h1 class="my-3 text-3xl font-semibold text-gray-800">Contact Us</h1>
                    <p class="text-gray-400">Fill up the form below to send us a message.</p>
                </div>
                <div class="m-7">
                    <form method="POST" id="form">
                        {% csrf_token %}
                        {# <input type="checkbox" name="botcheck" class="hidden" />#}

                        <div class="my-5">
                            <label for="name" class="block mb-2 text-sm text-gray-600">Full Name</label>
                            <input type="text" name="name" id="name" placeholder="John Doe" required
                                class="w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:ring-2 focus:ring-purple-500 focus:border-purple-500 focus:z-10" />
                        </div>
                        <div class="my-5">
                            <label for="email" class="block mb-2 text-sm text-gray-600">Email Address</label>
                            <input type="email" name="email" id="email" placeholder="you@company.com" required
                                class="w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:ring-2 focus:ring-purple-500 focus:border-purple-500 focus:z-10" />
                        </div>
                        <div class="my-5">
                            <label for="phone" class="block mb-2 text-sm text-gray-600">Phone Number</label>
                            <input type="text" name="phone" id="phone" placeholder="+880 1XXX XX XX XX"
                                class="w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:ring-2 focus:ring-purple-500 focus:border-purple-500 focus:z-10" />
                        </div>
                        <div class="my-5">
                            <label for="message" class="block mb-2 text-sm text-gray-600">Your Message</label>

                            <textarea rows="5" name="message" id="message" placeholder="Your Message"
                                class="w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:ring-2 focus:outline-none focus:ring-purple-600 focus:border-purple-600"
                                required></textarea>
                        </div>
                        <div class="my-5">
                            <button type="submit"
                                class="w-full py-4 px-4 border border-transparent font-medium rounded-md bg-gradient-to-r from-purple-600 to-fuchsia-500 tracking-wide text-base text-white hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500">Send
                                Message</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

scanimg/templates/scan.html
{% extends 'main.html' %}

{% block title %}Recognize{% endblock %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
	<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
	<link rel="icon" type="image/png" href="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Emojione_1F441.svg/2000px-Emojione_1F441.svg.png">
	<title>Tutorial</title>
    <link rel="stylesheet"  href="https://unpkg.com/swiper@8/swiper-bundle.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> 
     <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@200&family=Lato:ital,wght@1,300&family=Merienda:wght@400;700&family=Poppins:wght@400;500;600&family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
     <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css" />
	 <link rel="stylesheet" href="style.css" type="text/css">

     <style>
        h4 {
            text-align: center;
            color: purple;
            font-size: 30px;
            margin-bottom: 0;
            margin-top: 0;
        }
        #abc{
            margin-left: auto;
            margin-right: auto;
        }
   
        ol {
            color: black;
            text-align: left;
        }
    
        .notes {
            color: black;
            text-align: left;
        }
    
        a {
            color: black;
            text-decoration: none;
        }
  .text {
            color: DodgerBlue;
        }
    
    
        img {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 50%;
        }
    
        .instructions {
            margin: auto;
            width: 75%;
            border: 3px solid blue;
            padding: 10px;
            text-align: center;
        }
        .center {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 50%;
        }
    
        .numbers {
            font-size: 20px;
            color: RoyalBlue;
        }
    
        h3 {
            text-align: left;
        }
    
        .notes {
            text-align:left;
        }
    
    </style>
</head>
<body class="bg-light">
    <div>
        <br>
        <br>
        <br>
    </div>
    <div class="col-lg-8 px-lg-5" id="abc">
               <div class="border bg-light rounded p-4">
                    <h4 class="text-color-purple">Please Select an Image</h5>
                    <br>
                    <form method="POST" enctype="multipart/form-data">

                        {% csrf_token %}

                        <!-- {{ form.as_p }} -->
    
                            <label for="image"></label>
                            <input type="file" name="image" id="image" class="form-control" required  accept="image/*">
                             <br>
                             {% if obj %}
                             <div class="abc" id="hide">
                        
                                 <img src="{{ obj.image.url}}" alt="image" class="img-thumbnail" >
                             </div>
                            
                             {% endif %}
                             <hr>
                             <button class="btn btn-outline-dark  mb-10" name="add" type="submit">Scan</button>
    
                        
    
                    </form>
                    <hr>
              

                    <!-- <form method="post">{% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Send message">
                    </form> -->
    
                   
    
               </div>
    </div>
    <div>
        <br>
        <br>
        <br>
    </div>
<script>
 function myFunction(){
        var x=document.getElementById("hide");
        x.style.display ="block";
 }
     
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.7/lib/darkmode-js.min.js"></script>
<script src="https://kit.fontawesome.com/31a20b87d9.js" crossorigin="anonymous"></script>
</body>
</html>

{% endblock %}

templates/footer.html
<footer class="bg-gradient-to-r from-purple-600 to-fuchsia-600">
    <div class=" max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
        <div class="w-full text-white">
            <div class="pb-12 px-3 sm:px-0">
                <div class="w-full pt-12 flex flex-col sm:flex-row space-y-2 justify-around">
                    <div class="w-full mb-3 sm:w-2/5 pr-6 flex flex-col space-y-4 font-raleway">
                        <h3 class="text-3xl text-white font-siliguri font-semibold">
                            &#x1F9D1;&#x200D;&#x1F9AF; Scanner
                        </h3>
                    </div>
                    <div class="w-full sm:w-1/5 flex flex-col space-y-4">
                        <a href="{% url 'about' %}" class="opacity-70 text-gray-300 hover:opacity-100"><span
                                class="text-xl mr-2">&#8594;</span>About Us</a>
                        <a href="{% url 'help' %}" class="opacity-70 text-gray-300 hover:opacity-100"><span
                                class="text-xl mr-2">&#8594;</span>FAQ</a>
                
                        <a href="{% url 'contact:contact-us' %}" class="opacity-70 text-gray-300 hover:opacity-100"><span
                                class="text-xl mr-2">&#8594;</span>Contact</a>
                    </div>
                    <div class="w-full sm:w-1/5 flex flex-col space-y-4">
                        <a href="#" class="opacity-70 text-gray-300 hover:opacity-100"><span
                                class="text-xl mr-2">&#8594;</span>Report an issue</a>
                        <a href="#" class="opacity-70 text-gray-300 hover:opacity-100"><span
                                class="text-xl mr-2">&#8594;</span>Get Support</a>

                    </div>
                    <div class="w-full sm:w-1/5 pt-6 flex items-end mb-1">
                        <div class="flex flex-row space-x-4">
                            <i class="fab fa-facebook-f"></i>
                            <i class="fab fa-twitter"></i>
                            <i class="fab fa-instagram"></i>
                            <i class="fab fa-google"></i>
                        </div>
                    </div>
                </div>
                <hr class="my-5" />
                <div class="tracking-tight font-poppins font-light text-center sm:flex sm:justify-between">
                    <p class="text-gray-100">Made with <span class="text-rose-500">&hearts;</span> in Bangladesh</p>
                    <p class="text-gray-100">&copy; 2022 &#x1F9D1;&#x200D;&#x1F9AF; Scanner.</p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/index.html
{% extends 'main.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
   
</head>
<body>
    <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="container mx-auto my-10 col-md-5">
        <h1 class="my-3 text-3xl font-semibold text-gray-800">Scanner</h1>
        <p class="text-gray-400">Bridge the gap of communication between blind and non-blind people...</p>
    </div>
    <div class="col-md-7">
        <img src="static\media\1200x630wa.png" class="img-fluid rounded-start" alt="...">
      </div>
</div>

<script src="https://kit.fontawesome.com/31a20b87d9.js" crossorigin="anonymous"></script>
</html>

{% endblock %}

templates/main.html
{% extends 'base.html' %}

{% block style %}
<style>
    ::-webkit-scrollbar {
        width: 0.8rem;
    }

    ::-webkit-scrollbar-track {
        background: #FAE8FF;
        border-radius: 99rem;
    }

    ::-webkit-scrollbar-thumb {
        background: #F0ABFC;
        border-radius: 99rem;
    }

    ::-webkit-scrollbar-thumb:hover {
        background: #E879F9;
    }
</style>
{% endblock %}

{% block main %}
{% include 'nav.html' %}

{% block content %}

{% endblock %}

{% include 'footer.html' %}

{% endblock %}

templates/nav.html
{% load static %}

<nav class="bg-gradient-to-r from-purple-600 to-fuchsia-600 sticky-top">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-16">
      <div class="absolute left-0 inset-y-0 flex items-center sm:hidden">
        <!-- Mobile Menu Button -->
        <button
          id="menu-toggle"
          type="button"
          class="inline-flex items-center justify-center p-2 rounded-md text-gray-100 hover:bg-fuchsia-600 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-fuchsia-500"
        >
          <span class="sr-only">Open Main Menu</span>
          <svg
            id="hamburger"
            class="h-6 w-6 block"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            aria-hidden="true"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M4 6h16M4 12h16M4 18h16"
            ></path>
          </svg>
          <!--
                        Icon when menu is open.

                        Heroicon name: outline/x

                        Menu open: "block", Menu closed: "hidden"
                    -->
          <svg
            id="close"
            class="h-6 w-6 hidden"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            aria-hidden="true"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M6 18L18 6M6 6l12 12"
            ></path>
          </svg>
        </button>
      </div>
    <div
        class="flex flex-1 justify-center items-center sm:justify-start sm:items-stretch"
      >
        <a href="/" class="flex items-center flex-shrink-0">
          <!-- <img class="block lg:hidden h-8 w-auto"
                        src="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg" alt="Workflow" /> -->
          <!-- {# <img class="block h-8 w-auto" src="{% static 'shikhon/icon.svg' %}" alt="Shikhon" />#} -->
          <h1 class="sm:block text-white text-2xl font-semibold leading-3 px-2">
            &#x1F9D1;&#x200D;&#x1F9AF; Scanner
          </h1>
          <!-- <img class="hidden lg:block h-8 w-auto"
                        src="https://tailwindui.com/img/logos/workflow-logo-indigo-500-mark-white-text.svg"
                        alt="Workflow" /> -->
        </a>
        <div class="hidden sm:block sm:ml-6">
          <div class="flex space-x-4">
            {% if request.user.is_authenticated %}
            <a
              href="{% url 'scanimg:photo' %}"
              class="bg-fuchsia-600 text-white block px-3 py-2 rounded-md text-base font-medium"
              >Scan</a
            >
            {% endif %}
            <a
              href="{% url 'help' %}"
              class="text-white hover:bg-fuchsia-600 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
            >
             Help
            </a>
            <a
              href="{% url 'about' %}"
              class="text-white hover:bg-fuchsia-600 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
            >
              About
            </a>
            <a
              href="{% url 'contact:contact-us' %}"
              class="text-white hover:bg-fuchsia-600 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
            >
              Contact
            </a>
          </div>
        </div>
      </div>

    {% if request.user.is_authenticated %}
      <div class="absolute right-0 inset-y-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <button class="bg-purple-600 p-1 rounded-full text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-fuchsia-400 focus:ring-purple-700">
          <span class="sr-only">View notifications</span>
          <!-- Heroicon name: outline/bell -->
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-6 w-6"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"
            ></path>
          </svg>
        </button>

        <!-- Profile Dropdown -->
        <div class="ml-3 relative">
          <div>
            <button
              class="bg-purple-600 flex text-sm text-gray-300 rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-fuchsia-400 focus:ring-purple-700"
              id="user-menu"
              aria-haspopup="true"
            >
              <span class="sr-only">Open user menu</span>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-8 w-8"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                ></path>
              </svg>
              <!-- {# <img src="{% static 'shikhon/profile.jfif' %}" alt="Profile Image"
                                class="h-8 w-8 rounded-full object-cover" />#} -->
            </button>
          </div>

          <div
            id="user-dropdown"
            class="hidden absolute origin-top-right right-0 mt-2 w-48 rounded-md shadow-lg bg-fuchsia-600 ring-1 ring-purple-600 ring-opacity-5 focus:outline-none"
            role="menu"
            aria-orientation="vertical"
            aria-labelledby="user-menu"
          >
            <a
          
             href="{% url 'profile' request.user.username %}" 
              class="block px-4 py-2 rounded-t-md text-base text-gray-100 font-medium hover:bg-purple-600"
              role="menuitem"
              >Profile</a>
            <a
              href="{% url 'logout' %}"
              class="block px-4 py-2 rounded-b-md text-base text-gray-100 font-medium hover:bg-purple-600"
              role="menuitem"
              >Logout</a>
          </div>
        </div>
      </div>

    {% else %}
        <div
            class="absolute right-0 inset-y-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0"
        >
            <a
            href="{% url 'signup' %}"
            class="text-white hover:bg-fuchsia-600 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
            >
            Registration
            </a>
        </div>
        <div
        class="absolute right-0 inset-y-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0"
        >
        <a
            href="{% url 'login' %}"
            class="text-white hover:bg-fuchsia-600 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
        >
            Login
        </a>
        </div>
    {% endif %}
    </div>
  </div>

  <div id="mobile-menu" class="hidden sm:hidden">
    <div class="px-2 pt-2 pb-3 space-y-1">
    {% if request.user.is_authenticated %}
      <a
        href="{% url 'scanimg:photo' %}"
        class="bg-fuchsia-600 text-white block px-3 py-2 rounded-md text-base font-medium"
        >Scan</a
      >
    {% endif %}
      <a
        href="#"
        class="text-white hover:bg-fuchsia-600 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
      >
        Search
      </a>
      <a
        href="#"
        class="text-white hover:bg-fuchsia-600 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
      >
        Advanced
      </a>
      <a
        href="#"
        class="text-white hover:bg-fuchsia-600 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
      >
        Contact
      </a>
    </div>
  </div>
</nav>